---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kibana.name" . }}
    helm.sh/chart: {{ include "kibana.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kibana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if .Values.ingress.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dev-analytics-kibana-elb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    {{- if .Values.ingress.external.ssl }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.ingress.external.certArn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    {{ end }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ include "kibana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 80
    name: http
    targetPort: http
  {{- if .Values.ingress.external.ssl }}
  - port: 443
    name: https
    targetPort: http
  {{ end }}
{{ end }}
