---
apiVersion: v1
kind: Service
metadata:
  name: sortinghat-api-endpoint
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 32000
  selector:
    api-app: sortinghat-api
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sortinghat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      api-app: sortinghat-api
  template:
    metadata:
      labels:
        api-app: sortinghat-api
    spec:
      hostname: sortinghat-api
      containers:
        - name: sortinghat-api
          image: {IMAGE}
          ports:
            - containerPort: 80
          env:
            - name: WEB_CONCURRENCY
              value: '{WEB_CONCURENCY}'
            - name: FLASK_ENV
              value: '{FLASK_ENV}'
            - name: FLASK_DEBUG
              value: '{FLASK_DEBUG}'
            - name: LOG_LEVEL
              value: '{LOG_LEVEL}'
            - name: SORTINGHAT_DB_HOST
              value: '{SH_HOST}'
            - name: SORTINGHAT_DB_USER
              value: '{SH_USER}'
            - name: SORTINGHAT_DB_PASSWORD
              value: '{SH_PASS}'
            - name: SORTINGHAT_DB_DATABASE
              value: '{SH_DB}'
