apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
  name: dev-analytics-readonly
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  - policy
  - rbac.authorization.k8s.io
  - storage.k8s.io
  - autoscaling
  - authorization.k8s.io
  - apiextensions.k8s.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch