apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-elb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: SSLCERT
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    external-dns.alpha.kubernetes.io/hostname: HOSTNAME
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 9200
  - port: 443
    name: https
    targetPort: 9200
  selector:
    app: elasticsearch-master
