apiVersion: v1
kind: Secret
metadata:
  name: identity-api-env
type: Opaque
stringData:
  SORTINGHAT_DB_HOST: {{ $.Values.identity.db.host }}
  SORTINGHAT_DB_DATABASE: {{ $.Values.identity.db.name }}
  SORTINGHAT_DB_USER: {{ $.Values.identity.db.user }}
  SORTINGHAT_DB_PASSWORD: {{ $.Values.identity.db.password }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  labels:
    app.kubernetes.io/name: {{ include "grimoire-core.name" $ }}-identity-api
    helm.sh/chart: {{ include "grimoire-core.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grimoire-core.name" $ }}-identity-api
      app.kubernetes.io/instance: {{ $.Release.Name }}
      lfanalytics.io/service: identity-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grimoire-core.name" $ }}-identity-api
        app.kubernetes.io/instance: {{ $.Release.Name }}
        lfanalytics.io/service: identity-api
    spec:
      containers:
      - name: identity-api
        stdin: true 
        tty: true 
        image: "{{ $.Values.identity.image }}"
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        env:
        - name: FLASK_ENV
          value: "{{ $.Values.flask_env }}"
        - name: FLASK_DEBUG
          value: "{{ $.Values.flask_debug }}"
        - name: WEB_CONCURRENCY
          value: "{{ $.Values.web_concurency }}"
        - name: LOG_LEVEL
          value: "{{ $.Values.log_level }}"
        - name: PORT
          value: "9091"
        - name: SORTINGHAT_DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: identity-api-env
              key: SORTINGHAT_DB_DATABASE
        - name: SORTINGHAT_DB_USER
          valueFrom:
            secretKeyRef:
              name: identity-api-env
              key: SORTINGHAT_DB_USER
        - name: SORTINGHAT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: identity-api-env
              key: SORTINGHAT_DB_PASSWORD
        - name: SORTINGHAT_DB_HOST
          valueFrom:
            secretKeyRef:
              name: identity-api-env
              key: SORTINGHAT_DB_HOST
        ports:
        - containerPort: 9091
          name: identity
        resources:
          {{- toYaml $.Values.identityResources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{ end }}
