apiVersion: v1
kind: Service
metadata:
  name: arthurd
  labels:
    app.kubernetes.io/name: {{ include "grimoire-core.name" . }}-arthurd
    helm.sh/chart: {{ include "grimoire-core.chart" . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  ports:
  - port: 9090
    protocol: TCP
    name: arthurd
  selector:
    app.kubernetes.io/name: {{ include "grimoire-core.name" . }}-arthurd
    grimoire.lfanalytics.io/grimoire-service: arthurd
