kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-shared
  annotations:
    volume.beta.kubernetes.io/storage-class: '{{ $.Values.storageClass }}'
spec:
  storageClassName: '{{ $.Values.storageClass }}'
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
