---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: mariadb
  name: mariadb-backups
  labels:
    name: mariadb
    type: backups
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-openebs-localstorage
  resources:
    requests:
      storage: 40Gi
