---
apiVersion: v1
kind: Service
metadata:
  namespace: mariadb
  name: mariadb-service-all
  labels:
    app: mariadb-service-all
spec:
  ports:
  - name: http
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  namespace: mariadb
  name: mariadb-service-rw
  labels:
    app: mariadb-service-rw
spec:
  ports:
  - name: http
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
    component: master
  type: LoadBalancer
