---
apiVersion: v1
kind: Service
metadata:
  namespace: mariadb
  name: mariadb-service
  labels:
    app: mariadb
spec:
  ports:
  - name: http
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: LoadBalancer
