apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  labels:
    app: mariadb
type: Opaque
data:
  mariadb-root-password: PASS_ROOT
  mariadb-password: PASS_MAIN
  mariadb-replication-password: PASS_REP
