replicaCount: 1

api:
  url: 'set-me'
imagePullPolicy: Always
image: 'set-me'

identity:
  image: 'set-me'
  db:
    host: 'set-host'
    name: 'set-name'
    user: 'set-user'
    password: 'set-pass'

web_concurency: 1
flask_env: 'set-me'
flask_debug: 1
log_level: 'debug'

storageClass: 'nfs-openebs-localstorage'

resources:
  requests:
   cpu: 100m
   memory: 64Mi
arthurdResources:
  limits:
    cpu: 0.5
  requests:
   cpu: 100m
   memory: 256Mi
arthurwResources:
  limits:
    cpu: 1
  requests:
   cpu: 100m
   memory: 128Mi
mordredResources:
  limits:
    cpu: 1500m
  requests:
   cpu: 100m
   memory: 512Mi
identityResources:
  limits:
    cpu: 500m
  requests:
   cpu: 100m
   memory: 256Mi

arthurw:
  flags: ""

services:
- name: arthurd
  replicaCount: 1
  upgradeStrategy: Recreate
- name: arthurw
  replicaCount: 3
  upgradeStrategy: Recreate
- name: mordred
  replicaCount: 1
  upgradeStrategy: Recreate

useNodeSelector: 1
nodeSelector:
  lfda: grimoire

tolerations: []

affinity: {}
